[package]
name = "import-csv"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
csv = "1.3.1"
futures-util = "0.3.31"
postgres = "0.19.10"
reqwest = { version = "0.12.23", features = ["stream"] }
tokio = { version = "1.47.1", features = ["full"] }
