//! `GET /api/jobs`: the collections scheduled for one premise.
//!
//! Three formats: the JSON envelope the app reads, and a CSV or a calendar for
//! someone who would rather subscribe to the dates. Both files keep the shape
//! subscribed calendars already read.

use std::collections::HashMap;

use axum::Json;
use axum::extract::{Query, State};
use axum::http::header::{CONTENT_DISPOSITION, CONTENT_TYPE};
use axum::http::{HeaderMap, HeaderValue};
use axum::response::{IntoResponse, Response};
use chrono::NaiveDate;
use csv::Writer;
use icalendar::{Calendar, Component, Event, EventLike, Property, ValueType};
use sqlx::PgPool;

use crate::address;
use crate::search::{self, PremisesJobs};

use super::{ApiError, Envelope, Issue, one_of, premises_id, with_default};

/// The formats the endpoint serves.
const FORMATS: [&str; 3] = ["json", "csv", "ical"];

/// The site every collection links back to.
const SITE_URL: &str = "https://bins.felixyeung.com";

/// Collections are whole days, so this only says where the site is.
const TIMEZONE: &str = "Europe/London";

/// `GET /api/jobs?premises=<id>[&format=json|csv|ical]`
pub async fn handler(
    State(pool): State<PgPool>,
    Query(query): Query<HashMap<String, String>>,
) -> Result<Response, ApiError> {
    let (premises, format) = parse(&query).map_err(ApiError::Invalid)?;

    let data = search::jobs(&pool, premises)
        .await?
        .ok_or(ApiError::NotFound("Premises not found"))?;

    Ok(match format {
        "csv" => download(&data, "csv", "text/csv", csv(&data)?)?,
        "ical" => download(&data, "ics", "text/calendar", ical(&data))?,
        _ => Json(Envelope::ok(data)).into_response(),
    })
}

/// Reads the query string, checking every parameter so the response lists every
/// problem at once rather than only the first.
fn parse(query: &HashMap<String, String>) -> Result<(i32, &str), Vec<Issue>> {
    let premises = premises_id(query);
    let format = one_of(with_default(query, "format", "json"), "format", &FORMATS);

    let issues: Vec<Issue> = [
        premises.as_ref().err().cloned(),
        format.as_ref().err().cloned(),
    ]
    .into_iter()
    .flatten()
    .collect();

    if let (Ok(premises), Ok(format)) = (premises, format) {
        return Ok((premises, format));
    }

    Err(issues)
}

/// A file for the caller to save rather than read, named after the premise and
/// the format it is written in.
fn download(
    data: &PremisesJobs,
    extension: &str,
    content_type: &'static str,
    body: String,
) -> Result<Response, ApiError> {
    let mut headers = HeaderMap::new();
    headers.insert(CONTENT_TYPE, HeaderValue::from_static(content_type));
    headers.insert(
        CONTENT_DISPOSITION,
        HeaderValue::from_str(&format!(
            "attachment; filename=\"jobs-{}.{extension}\"",
            data.premises.id
        ))?,
    );

    Ok((headers, body).into_response())
}

/// The collections as a CSV: a `Date,Bin` header, then a row per collection
/// with the bin last.
fn csv(data: &PremisesJobs) -> Result<String, ApiError> {
    let mut writer = Writer::from_writer(Vec::new());

    writer.write_record(["Date", "Bin"])?;
    for job in &data.jobs {
        writer.write_record([job.date.to_string(), job.bin.clone()])?;
    }

    Ok(String::from_utf8(writer.into_inner()?)?)
}

/// The collections as a calendar: one all day event per collection, named after
/// the bin and linking to the date on the site.
fn ical(data: &PremisesJobs) -> String {
    let id = data.premises.id;
    let address = address::full(&data.premises);

    let mut calendar = Calendar::new();
    calendar.name(&format!(
        "Bin Days for {}",
        address::summary(&data.premises)
    ));
    calendar.description(&format!(
        "Bin collection dates for your household\n\n{address}\n\nID: {id}\n\nGenerated by {SITE_URL}"
    ));
    // Both spellings are emitted, so subscribed calendars keep whichever one
    // their app reads.
    calendar.append_property(Property::new("X-WR-TIMEZONE", TIMEZONE));
    calendar.append_property(Property::new("TIMEZONE-ID", TIMEZONE));

    for job in &data.jobs {
        let mut event = Event::new();
        event
            .uid(&format!("{id}_{}_{}", job.date, job.bin))
            .summary(&format!("{} Bin Collection", capital_case(&job.bin)))
            .location(&address)
            .all_day(job.date);
        // `Event::url` leaves off the value type, without which some calendar
        // apps do not treat the property as a link.
        event.append_property(
            Property::new("URL", premise_url(id, job.date, &job.bin))
                .append_parameter(ValueType::Uri)
                .done(),
        );

        calendar.push(event.done());
    }

    calendar.to_string()
}

/// Where one collection is shown on the site.
fn premise_url(id: i32, date: NaiveDate, bin: &str) -> String {
    format!("{SITE_URL}/premises?id={id}&date={date}&bin={bin}")
}

/// `change-case`'s `capitalCase`, which is what puts the bin name in each event
/// summary in title case.
///
/// Words are split on anything that is not a letter or a digit, and wherever a
/// capital letter follows something that is not one, then each word is
/// capitalised and joined with a space. That is why `GENERAL WASTE` reads as
/// `General Waste` while `GENERALWASTE` stays one word.
fn capital_case(value: &str) -> String {
    let mut words: Vec<String> = Vec::new();
    let mut word = String::new();
    let mut previous: Option<char> = None;

    for character in value.chars() {
        if !character.is_alphanumeric() {
            if !word.is_empty() {
                words.push(std::mem::take(&mut word));
            }
            previous = None;
            continue;
        }

        let starts_a_word =
            previous.is_some_and(|previous| !previous.is_uppercase() && character.is_uppercase());

        if starts_a_word && !word.is_empty() {
            words.push(std::mem::take(&mut word));
        }

        word.extend(character.to_lowercase());
        previous = Some(character);
    }

    if !word.is_empty() {
        words.push(word);
    }

    words
        .iter()
        .map(|word| {
            let mut characters = word.chars();
            let first = characters
                .next()
                .map_or_else(String::new, |first| first.to_uppercase().to_string());

            first + characters.as_str()
        })
        .collect::<Vec<String>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use chrono::{DateTime, Utc};
    use icalendar::parser::{Property as ParsedProperty, read_calendar, unfold};

    use crate::search::{Job, Premises};

    use super::*;

    fn query(pairs: &[(&str, &str)]) -> HashMap<String, String> {
        pairs
            .iter()
            .map(|(key, value)| (key.to_string(), value.to_string()))
            .collect()
    }

    fn day(value: &str) -> NaiveDate {
        NaiveDate::parse_from_str(value, "%Y-%m-%d").expect("a date")
    }

    fn data(room: Option<&str>, number: Option<&str>, jobs: &[(&str, &str)]) -> PremisesJobs {
        PremisesJobs {
            premises: Premises {
                id: 1_000_001,
                address_room: room.map(str::to_string),
                address_number: number.map(str::to_string),
                address_street: Some("SHARP MEWS".to_string()),
                address_locality: Some("MEANWOOD".to_string()),
                address_city: Some("LEEDS".to_string()),
                address_postcode: Some("LS6 2SE".to_string()),
                updated_at: DateTime::<Utc>::UNIX_EPOCH,
            },
            jobs: jobs
                .iter()
                .map(|(bin, date)| Job {
                    bin: (*bin).to_string(),
                    date: day(date),
                })
                .collect(),
        }
    }

    #[test]
    fn json_is_the_default_format() {
        assert_eq!(parse(&query(&[("premises", "1")])).unwrap().1, "json");
        assert_eq!(
            parse(&query(&[("premises", "1"), ("format", "json")]))
                .unwrap()
                .1,
            "json"
        );
    }

    #[test]
    fn reads_the_premises_id() {
        assert_eq!(parse(&query(&[("premises", "4242")])).unwrap().0, 4242);
    }

    #[test]
    fn reports_every_problem_at_once() {
        let issues = parse(&query(&[("premises", "abc"), ("format", "xml")])).unwrap_err();

        assert_eq!(
            issues,
            vec![
                Issue::not_a_number("premises"),
                Issue::not_an_option("format", "xml", &FORMATS),
            ]
        );
    }

    #[test]
    fn a_csv_is_a_date_and_a_bin_per_collection() {
        let data = data(
            None,
            Some("6"),
            &[("GREEN", "2026-11-02"), ("BLACK", "2026-11-09")],
        );

        assert_eq!(
            csv(&data).unwrap(),
            "Date,Bin\n2026-11-02,GREEN\n2026-11-09,BLACK\n"
        );
    }

    #[test]
    fn a_csv_of_a_premise_with_no_collections_is_its_header() {
        assert_eq!(
            csv(&data(None, Some("6"), &[])).unwrap(),
            "Date,Bin\n".to_string()
        );
    }

    #[test]
    fn a_bin_containing_the_separator_is_quoted() {
        let data = data(None, Some("6"), &[("GENERAL, WASTE", "2026-11-02")]);

        assert_eq!(
            csv(&data).unwrap(),
            "Date,Bin\n2026-11-02,\"GENERAL, WASTE\"\n"
        );
    }

    /// A written calendar read back through the parser, as the properties of the
    /// calendar itself and one set per event.
    struct Written {
        calendar: Properties,
        events: Vec<Properties>,
    }

    /// The properties of one component, in the order they were written.
    type Properties = Vec<(String, String)>;

    /// What `/api/jobs?format=ical` writes for a premise, read back through the
    /// parser. The parser wants folded lines joined up first, which is what the
    /// crate does for itself when it reads back one of its own calendars.
    fn written(data: &PremisesJobs) -> Written {
        let body = unfold(&ical(data));
        let calendar = read_calendar(&body).expect("a calendar the parser accepts");

        Written {
            calendar: properties(&calendar.properties),
            events: calendar
                .components
                .iter()
                .filter(|component| component.name.as_str() == "VEVENT")
                .map(|event| properties(&event.properties))
                .collect(),
        }
    }

    /// Every property of a component, unescaped and owned, which is how a
    /// calendar app reads them.
    fn properties(properties: &[ParsedProperty]) -> Properties {
        properties
            .iter()
            .map(|property| {
                (
                    property.name.to_owned().into_owned().as_str().to_owned(),
                    property
                        .val
                        .clone()
                        .unescape_by_value_type(ValueType::Text)
                        .into_owned()
                        .as_str()
                        .to_owned(),
                )
            })
            .collect()
    }

    /// The value of one property.
    fn property<'a>(properties: &'a Properties, name: &str) -> Option<&'a str> {
        properties
            .iter()
            .find(|(key, _)| key == name)
            .map(|(_, value)| value.as_str())
    }

    #[test]
    fn a_calendar_is_named_after_the_address_and_says_where_it_is_for() {
        let written = written(&data(Some("FLAT 1"), Some("6"), &[("GREEN", "2026-11-02")]));

        assert_eq!(
            property(&written.calendar, "X-WR-CALNAME"),
            Some("Bin Days for FLAT 1 6 SHARP MEWS"),
            "the calendar is named after the household"
        );
        assert_eq!(
            property(&written.calendar, "X-WR-CALDESC"),
            Some(
                "Bin collection dates for your household\n\n\
                 FLAT 1\n6\nSHARP MEWS\nMEANWOOD\nLEEDS\nLS6 2SE\n\n\
                 ID: 1000001\n\nGenerated by https://bins.felixyeung.com"
            )
        );
        assert_eq!(
            property(&written.calendar, "X-WR-TIMEZONE"),
            Some("Europe/London")
        );
        assert_eq!(property(&written.calendar, "VERSION"), Some("2.0"));
    }

    #[test]
    fn a_calendar_holds_a_collection_per_event() {
        let written = written(&data(Some("FLAT 1"), Some("6"), &[("GREEN", "2026-11-02")]));

        assert_eq!(written.events.len(), 1);

        let event = &written.events[0];

        assert_eq!(property(event, "UID"), Some("1000001_2026-11-02_GREEN"));
        assert_eq!(property(event, "SUMMARY"), Some("Green Bin Collection"));
        assert_eq!(
            property(event, "LOCATION"),
            Some("FLAT 1\n6\nSHARP MEWS\nMEANWOOD\nLEEDS\nLS6 2SE"),
            "a collection is collected from the address"
        );
        assert_eq!(
            property(event, "URL"),
            Some("https://bins.felixyeung.com/premises?id=1000001&date=2026-11-02&bin=GREEN"),
            "the event links to the date it collects on"
        );
        assert_eq!(property(event, "URL;VALUE=URI"), None);
        // Both ends are the day of the collection, which is how `ical-generator`
        // wrote an all day event.
        assert_eq!(property(event, "DTSTART"), Some("20261102"));
        assert_eq!(property(event, "DTEND"), Some("20261102"));
        assert!(
            property(event, "DTSTAMP").is_some(),
            "an event says when it was written"
        );
    }

    #[test]
    fn a_calendar_holds_the_collections_in_order() {
        let written = written(&data(
            None,
            Some("6"),
            &[("GREEN", "2026-11-02"), ("BLACK", "2026-11-09")],
        ));

        let uids: Vec<Option<&str>> = written
            .events
            .iter()
            .map(|event| property(event, "UID"))
            .collect();

        assert_eq!(
            uids,
            vec![
                Some("1000001_2026-11-02_GREEN"),
                Some("1000001_2026-11-09_BLACK"),
            ]
        );
    }

    #[test]
    fn a_calendar_of_a_premise_with_no_collections_is_still_a_calendar() {
        let written = written(&data(None, Some("6"), &[]));

        assert_eq!(written.events.len(), 0);
        assert_eq!(
            property(&written.calendar, "X-WR-CALNAME"),
            Some("Bin Days for 6 SHARP MEWS")
        );
    }

    #[test]
    fn a_collection_is_named_after_its_bin() {
        let written = written(&data(
            None,
            Some("6"),
            &[("GREEN", "2026-11-02"), ("GENERAL WASTE", "2026-11-09")],
        ));

        let summaries: Vec<Option<&str>> = written
            .events
            .iter()
            .map(|event| property(event, "SUMMARY"))
            .collect();

        assert_eq!(
            summaries,
            vec![
                Some("Green Bin Collection"),
                Some("General Waste Bin Collection"),
            ]
        );
    }

    #[test]
    fn a_collection_links_to_the_date_rather_than_the_premise() {
        assert_eq!(
            premise_url(42, day("2026-11-02"), "GREEN"),
            "https://bins.felixyeung.com/premises?id=42&date=2026-11-02&bin=GREEN"
        );
    }

    #[test]
    fn bin_names_are_capitalised_the_way_change_case_capitalised_them() {
        // The cases match `capitalCase` in `change-case`.
        for (value, expected) in [
            ("BLACK", "Black"),
            ("GENERAL WASTE", "General Waste"),
            ("GENERALWASTE", "Generalwaste"),
            ("MixedCase", "Mixed Case"),
            ("mixedCase", "Mixed Case"),
            ("GLASS  WASTE", "Glass Waste"),
            ("A-B", "A B"),
            ("12 MONTHS", "12 Months"),
            ("Bin2Go", "Bin2 Go"),
            ("ABC123", "Abc123"),
            ("123ABC", "123 Abc"),
            ("a1b2", "A1b2"),
            ("GLASS2GO", "Glass2 Go"),
            ("N34W", "N34 W"),
            ("x-ray", "X Ray"),
            ("PDF", "Pdf"),
            ("a  b", "A B"),
            ("üBER", "Ü Ber"),
            ("two  spaces", "Two Spaces"),
            ("3-4-5", "3 4 5"),
            ("O'BRIEN", "O Brien"),
            ("row_2_col", "Row 2 Col"),
        ] {
            assert_eq!(capital_case(value), expected, "{value:?}");
        }
    }
}
