version: "3.7"

services:
  db:
    image: postgres:17.6-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data

  worker:
    image: registry.digitalocean.com/felixyeung/bins:worker
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/db
    depends_on:
      - db

  web:
    image: registry.digitalocean.com/felixyeung/bins:web
    restart: unless-stopped
    secrets:
      - upstash_redis_rest_url
      - upstash_redis_rest_token
      - rapid_api_proxy_secret
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/db
      - UPSTASH_REDIS_REST_URL_FILE=/run/secrets/upstash_redis_rest_url
      - UPSTASH_REDIS_REST_TOKEN_FILE=/run/secrets/upstash_redis_rest_token
      - RAPID_API_PROXY_SECRET_FILE=/run/secrets/rapid_api_proxy_secret
      - SKIP_SITEMAP=""
    depends_on:
      - db

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    secrets:
      - tunnel_token
    environment:
      - TUNNEL_TOKEN_FILE=/run/secrets/tunnel_token

  migration:
    image: registry.digitalocean.com/felixyeung/bins:migration
    restart: "no"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/db
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: none

secrets:
  tunnel_token:
    external: true
  upstash_redis_rest_url:
    external: true
  upstash_redis_rest_token:
    external: true
  rapid_api_proxy_secret:
    external: true

volumes:
  db-data:
