version: "3.7"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./data/prod/db:/var/lib/postgresql/data
    ports:
      - "56432:5432"

  worker:
    build:
      dockerfile: Dockerfile
      target: worker
    restart: unless-stopped
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/db
    depends_on:
      - db

  web:
    build:
      dockerfile: Dockerfile
      target: web
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
