version: "3.7"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./data/prod/db:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/db
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - 25555:80
