version: "3.7"

services:
  db:
    image: postgres:17.6-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./data/prod/db:/var/lib/postgresql/data
    ports:
      - "56432:5432"

  worker:
    build:
      dockerfile: Dockerfile
      target: worker
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/db
    depends_on:
      - db

  web:
    build:
      dockerfile: Dockerfile
      target: web
    restart: unless-stopped
    secrets:
      - upstash_redis_rest_url
      - upstash_redis_rest_token
      - rapid_api_proxy_secret
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/db
      - UPSTASH_REDIS_REST_URL_FILE=/run/secrets/upstash_redis_rest_url
      - UPSTASH_REDIS_REST_TOKEN_FILE=/run/secrets/upstash_redis_rest_token
      - RAPID_API_PROXY_SECRET_FILE=/run/secrets/rapid_api_proxy_secret
    depends_on:
      - db
    ports:
      - 3000:3000

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    secrets:
      - tunnel_token
    environment:
      - TUNNEL_TOKEN_FILE=/run/secrets/tunnel_token

  migration:
    build:
      dockerfile: Dockerfile
      target: migration
    restart: "no"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/db
    depends_on:
      - db

secrets:
  tunnel_token:
   external: true
  upstash_redis_rest_url:
   external: true
  upstash_redis_rest_token:
   external: true
  rapid_api_proxy_secret:
   external: true
   