name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build
        run: make DOCKER_BUILD_FLAGS='--load --cache-to type=gha,mode=max,scope=image-$* --cache-from type=gha,scope=image-$*' image-build

      - name: Docker tag
        run: make image-tag

      - name: Docker push
        if: ${{ github.event_name != 'pull_request' }}
        run: make registry-push
